services:
  stirling-pdf:
    image: hisham55990/hq-pdf:latest
    container_name: stirling-pdf
    restart: unless-stopped

    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -f http://localhost:8080$${SYSTEM_ROOTURIPATH:-''}/api/v1/info/status | grep -q 'UP'"
        ]
      interval: 10s
      timeout: 10s
      retries: 16
      start_period: 30s

    ports:
      - "8081:8080"

    volumes:
      - ../../stirling/latest/data:/usr/share/tessdata:rw
      - ../../stirling/latest/config:/configs:rw
      - ../../stirling/latest/logs:/logs:rw

    environment:
      DISABLE_ADDITIONAL_FEATURES: "true"
      SECURITY_ENABLELOGIN: "false"

      SYSTEM_DEFAULTLOCALE: "en-US"
      SYSTEM_MAXFILESIZE: "100"
      SYSTEM_GOOGLEVISIBILITY: "true"

      UI_APPNAME: "HQ-PDF"
      UI_HOMEDESCRIPTION: "HQ PDF - PDF Tools"
      UI_APPNAMENAVBAR: "HQ-PDF"

      METRICS_ENABLED: "true"
      SHOW_SURVEY: "true"

    networks:
      - stirling-network

networks:
  stirling-network:
    driver: bridge
