name: Generate PDF Document

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-pdf:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v7

      - name: Install Pandoc and wkhtmltopdf
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc wkhtmltopdf

      - name: Convert Markdown to PDF
        run: |
          pandoc document.md -o document.pdf --pdf-engine=wkhtmltopdf

      - name: Upload PDF Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Generated-PDF-File
          path: document.pdf
